language: ruby

branches:
  only:
  - master

before_install:
- gem install bundler jekyll

install:
- bundle install

before_script:
- git config --global user.name 'Kyle M Hall'
- git config --global user.email 'kyle@bywatersolutions.com'

script:
# Short circuite infinite loop of site updating
- octopod build -d ./docs
- git add docs
- git status
- git commit --allow-empty -m 'Site auto-updated [ci skip]'
- git status
- git remote add github https://$GH_TOKEN@github.com/bywatersolutions/libraryisopen.com.git
- git push github HEAD:master
