language: ruby

branches:
  only:
  - master

before_install:
- gem install bundler jekyll

install:
- bundle install

before_script:
- git config --global user.name 'Kyle M Hall'
- git config --global user.email 'kyle@bywatersolutions.com'

script:
# Short circuite infinite loop of site updating
- git log -1 --pretty=oneline | grep 'Site auto-updated' || octopod build -d ./docs
- git add docs
- git status
- git log -1 --pretty=oneline | grep 'Site auto-updated' || git commit -m 'Site auto-updated'
- git status
- git remote add github https://$GH_TOKEN@github.com/bywatersolutions/libraryisopen.com.git
- git push github HEAD:master
