name: CI
on: [push]
jobs:
  build:
    name: Build & deploy
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Configure git
      run: |
        git config --local user.name 'Kyle M Hall'
        git config --local user.email 'kyle@bywatersolutions.com'

    - name: Install bundler
      run: sudo gem install bundler:1.16.1

    - name: Install bundle
      run: sudo bundle install

    - name: Build
      run: octopod build -d ./docs

    - name: Add to repo
      run: git add docs

    - name: Show status
      run: git status

    - name: Commit to repo
      run: git commit --allow-empty -m 'Site auto-updated [ci skip]'

    - name: Push to master
      run: git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/bywatersolutions/libraryisopen.com.git HEAD:master
