name: CI
on: [push]
jobs:
  build:
    name: Run unit tests
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install bundler
      run: gem install bundler

    - name: Install bundle
      run: bundle install
      
    - name: Configure git
      run: |
        git config --global user.name 'Kyle M Hall'
        git config --global user.email 'kyle@bywatersolutions.com'

    - name: Build
      run: octopod build -d ./docs

    - name: Add to repo
      run: git add docs

    - name: Show status
      run: git status

    - name: Commit to repo
      run: git commit --allow-empty -m 'Site auto-updated [ci skip]'

    - name: Add remote for pushing
      run: git remote add github https://$GH_TOKEN@github.com/bywatersolutions/libraryisopen.com.git
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Push to master
      run: git push github HEAD:master
